class Country {
  final String flag;
  final String name;
  final String dialCode;

  Country({required this.flag, required this.name, required this.dialCode});
}

// List of sample countries (expand this as needed)

List<Country> countries = [
  Country(flag: "🇦🇫", name: "Afghanistan", dialCode: "+93"),
  Country(flag: "🇦🇱", name: "Albania", dialCode: "+355"),
  Country(flag: "🇩🇿", name: "Algeria", dialCode: "+213"),
  Country(flag: "🇦🇩", name: "Andorra", dialCode: "+376"),
  Country(flag: "🇦🇴", name: "Angola", dialCode: "+244"),
  Country(flag: "🇦🇷", name: "Argentina", dialCode: "+54"),
  Country(flag: "🇦🇲", name: "Armenia", dialCode: "+374"),
  Country(flag: "🇦🇺", name: "Australia", dialCode: "+61"),
  Country(flag: "🇦🇹", name: "Austria", dialCode: "+43"),
  Country(flag: "🇦🇿", name: "Azerbaijan", dialCode: "+994"),
  Country(flag: "🇧🇭", name: "Bahrain", dialCode: "+973"),
  Country(flag: "🇧🇩", name: "Bangladesh", dialCode: "+880"),
  Country(flag: "🇧🇧", name: "Barbados", dialCode: "+1"),
  Country(flag: "🇧🇾", name: "Belarus", dialCode: "+375"),
  Country(flag: "🇧🇪", name: "Belgium", dialCode: "+32"),
  Country(flag: "🇧🇷", name: "Brazil", dialCode: "+55"),
  Country(flag: "🇨🇦", name: "Canada", dialCode: "+1"),
  Country(flag: "🇨🇳", name: "China", dialCode: "+86"),
  Country(flag: "🇨🇴", name: "Colombia", dialCode: "+57"),
  Country(flag: "🇨🇺", name: "Cuba", dialCode: "+53"),
  Country(flag: "🇨🇾", name: "Cyprus", dialCode: "+357"),
  Country(flag: "🇨🇿", name: "Czech Republic", dialCode: "+420"),
  Country(flag: "🇩🇰", name: "Denmark", dialCode: "+45"),
  Country(flag: "🇪🇬", name: "Egypt", dialCode: "+20"),
  Country(flag: "🇫🇷", name: "France", dialCode: "+33"),
  Country(flag: "🇩🇪", name: "Germany", dialCode: "+49"),
  Country(flag: "🇬🇭", name: "Ghana", dialCode: "+233"),
  Country(flag: "🇬🇷", name: "Greece", dialCode: "+30"),
  Country(flag: "🇭🇰", name: "Hong Kong", dialCode: "+852"),
  Country(flag: "🇮🇳", name: "India", dialCode: "+91"),
  Country(flag: "🇮🇩", name: "Indonesia", dialCode: "+62"),
  Country(flag: "🇮🇪", name: "Ireland", dialCode: "+353"),
  Country(flag: "🇮🇱", name: "Israel", dialCode: "+972"),
  Country(flag: "🇮🇹", name: "Italy", dialCode: "+39"),
  Country(flag: "🇯🇵", name: "Japan", dialCode: "+81"),
  Country(flag: "🇰🇪", name: "Kenya", dialCode: "+254"),
  Country(flag: "🇰🇷", name: "South Korea", dialCode: "+82"),
  Country(flag: "🇱🇰", name: "Sri Lanka", dialCode: "+94"),
  Country(flag: "🇲🇾", name: "Malaysia", dialCode: "+60"),
  Country(flag: "🇲🇽", name: "Mexico", dialCode: "+52"),
  Country(flag: "🇳🇱", name: "Netherlands", dialCode: "+31"),
  Country(flag: "🇳🇿", name: "New Zealand", dialCode: "+64"),
  Country(flag: "🇳🇬", name: "Nigeria", dialCode: "+234"),
  Country(flag: "🇳🇴", name: "Norway", dialCode: "+47"),
  Country(flag: "🇵🇰", name: "Pakistan", dialCode: "+92"),
  Country(flag: "🇵🇭", name: "Philippines", dialCode: "+63"),
  Country(flag: "🇵🇱", name: "Poland", dialCode: "+48"),
  Country(flag: "🇵🇹", name: "Portugal", dialCode: "+351"),
  Country(flag: "🇶🇦", name: "Qatar", dialCode: "+974"),
  Country(flag: "🇷🇺", name: "Russia", dialCode: "+7"),
  Country(flag: "🇸🇦", name: "Saudi Arabia", dialCode: "+966"),
  Country(flag: "🇸🇬", name: "Singapore", dialCode: "+65"),
  Country(flag: "🇿🇦", name: "South Africa", dialCode: "+27"),
  Country(flag: "🇪🇸", name: "Spain", dialCode: "+34"),
  Country(flag: "🇸🇪", name: "Sweden", dialCode: "+46"),
  Country(flag: "🇨🇭", name: "Switzerland", dialCode: "+41"),
  Country(flag: "🇹🇭", name: "Thailand", dialCode: "+66"),
  Country(flag: "🇹🇷", name: "Turkey", dialCode: "+90"),
  Country(flag: "🇺🇦", name: "Ukraine", dialCode: "+380"),
  Country(flag: "🇦🇪", name: "United Arab Emirates", dialCode: "+971"),
  Country(flag: "🇬🇧", name: "United Kingdom", dialCode: "+44"),
  Country(flag: "🇺🇸", name: "United States", dialCode: "+1"),
  Country(flag: "🇻🇳", name: "Vietnam", dialCode: "+84"),
  Country(flag: "🇿🇼", name: "Zimbabwe", dialCode: "+263"),
  Country(flag: "🇨🇬", name: "Congo", dialCode: "+242"),
  Country(flag: "🇪🇹", name: "Ethiopia", dialCode: "+251"),
  Country(flag: "🇲🇦", name: "Morocco", dialCode: "+212"),
  Country(flag: "🇳🇵", name: "Nepal", dialCode: "+977"),
  Country(flag: "🇸🇩", name: "Sudan", dialCode: "+249"),
  Country(flag: "🇹🇳", name: "Tunisia", dialCode: "+216"),
  Country(flag: "🇺🇬", name: "Uganda", dialCode: "+256"),
  Country(flag: "🇻🇪", name: "Venezuela", dialCode: "+58"),
];
